hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]

    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    resource_owners:
        google:
            type:                google
            client_id:           '%env(GOOGLE_CLIENT_ID)%'
            client_secret:       '%env(GOOGLE_CLIENT_TOKEN)%'
            scope:               "email profile"
        vk:
            type:                vkontakte
            client_id:           '%env(VK_CLIENT_ID)%'
            client_secret:       '%env(VK_CLIENT_TOKEN)%'