knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_TOKEN)%'
            redirect_route: google_auth
            redirect_params: {}
        vk:
            type: vkontakte
            client_id: '%env(VK_CLIENT_ID)%'
            client_secret: '%env(VK_CLIENT_TOKEN)%'
            redirect_route: vk_auth
            redirect_params: {} 