knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_TOKEN)%'
            redirect_route: google_auth
            redirect_params: {}
        facebook:
            type: facebook
            client_id: '%env(FACEBOOK_CLIENT_ID)%'
            client_secret: '%env(FACEBOOK_CLIENT_TOKEN)%'
            redirect_route: facebook_auth
            redirect_params: {} 
            graph_api_version: v2.12