version: '3.3'

services:
  nginx:
    image: nginx:1.20
    ports:
      - 80:80
    volumes:
      - ./:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  php:
    build: ./.docker/php
    working_dir: /var/www/php
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/php
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - mariadb
      - pgsql
          
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb-data:/var/lib/mysql
      
  pgsql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    volumes:
      - pgsql-data:/var/lib/pgsql
      
  pgadmin:
    image: dpage/pgadmin4:6.4
    environment:
      PGADMIN_DEFAULT_EMAIL: roma.ivanov.1920@mail.ru
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_LISTEN_PORT: 80
    ports: 
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - pgsql:pgsql-server
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    links:
      - mariadb:db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    volumes:
      - pma-data:/var/lib/pma


volumes:
  mariadb-data:
  pgsql-data:
  pgadmin-data:
  pma-data:
